import { MyCliError } from '@mycli/core';
import { type FileSystem, createFileSystem } from '@mycli/filesystem';
import { createTemplateEngine } from '@mycli/template-engine';
import { execa } from 'execa';
import {
  COMMUNITY_FILES,
  type GitCommunityOptions,
  type GitHooksOptions,
  type GitHooksResult,
  HOOK_FILES,
  commitlintExtends,
  hookCommands,
  hooksDevDependencies,
} from './community.js';
import { getGitProviderAdapter } from './providers/index.js';
import type {
  BranchStrategy,
  CreateRemoteRepoOptions,
  CreateRemoteRepoResult,
  GitInitOptions,
  GitProvider,
  PublishToRemoteOptions,
  PublishToRemoteResult,
  RemoteOptions,
} from './types.js';

/**
 * Git lifecycle management: init, remotes, commits, provider repository creation, and push.
 */
export class GitManager {
  private readonly cwd: string;

  constructor(options: { cwd?: string; filesystem?: FileSystem } = {}) {
    this.cwd = options.cwd ?? process.cwd();
    void options.filesystem;
  }

  async isAvailable(): Promise<boolean> {
    try {
      const result = await execa('git', ['--version'], { reject: false });
      return result.exitCode === 0;
    } catch {
      return false;
    }
  }

  async isRepository(cwd = this.cwd): Promise<boolean> {
    const result = await execa('git', ['rev-parse', '--is-inside-work-tree'], {
      cwd,
      reject: false,
    });
    return result.exitCode === 0 && result.stdout.trim() === 'true';
  }

  async hasCommits(cwd = this.cwd): Promise<boolean> {
    const result = await execa('git', ['rev-parse', 'HEAD'], { cwd, reject: false });
    return result.exitCode === 0;
  }

  async init(options: GitInitOptions = {}): Promise<void> {
    const cwd = options.cwd ?? this.cwd;
    if (!(await this.isAvailable())) {
      throw new MyCliError('Git is not installed', { code: 'GIT_ERROR' });
    }
    if (await this.isRepository(cwd)) {
      return;
    }
    const branch = options.defaultBranch ?? 'main';
    const initWithBranch = await execa('git', ['init', '-b', branch], { cwd, reject: false });
    if (initWithBranch.exitCode !== 0) {
      const initFallback = await execa('git', ['init'], { cwd, reject: false });
      if (initFallback.exitCode !== 0) {
        throw new MyCliError(
          `git init failed: ${initFallback.stderr || initFallback.stdout || 'unknown error'}`,
          { code: 'GIT_ERROR' },
        );
      }
      const checkout = await execa('git', ['checkout', '-b', branch], { cwd, reject: false });
      if (checkout.exitCode !== 0) {
        await execa('git', ['branch', '-M', branch], { cwd, reject: false });
      }
    }
    await this.ensureLocalIdentity(cwd);
  }

  /** Set local git identity when missing so initial commits succeed in CI/sandboxes. */
  private async ensureLocalIdentity(cwd: string): Promise<void> {
    const name = await execa('git', ['config', 'user.name'], { cwd, reject: false });
    if (!name.stdout.trim()) {
      await execa('git', ['config', 'user.name', 'MyCLI'], { cwd });
    }
    const email = await execa('git', ['config', 'user.email'], { cwd, reject: false });
    if (!email.stdout.trim()) {
      await execa('git', ['config', 'user.email', 'mycli@local.dev'], { cwd });
    }
  }

  async addAll(cwd = this.cwd): Promise<void> {
    await execa('git', ['add', '.'], { cwd });
  }

  async commit(message: string, cwd = this.cwd): Promise<void> {
    await execa('git', ['commit', '-m', message], { cwd });
  }

  async addRemote(options: RemoteOptions): Promise<void> {
    const cwd = options.cwd ?? this.cwd;
    const name = options.name ?? 'origin';
    const existing = await execa('git', ['remote'], { cwd });
    if (
      existing.stdout
        .split('\n')
        .map((s) => s.trim())
        .includes(name)
    ) {
      await execa('git', ['remote', 'set-url', name, options.url], { cwd });
      return;
    }
    await execa('git', ['remote', 'add', name, options.url], { cwd });
  }

  async push(
    options: {
      cwd?: string;
      remote?: string;
      branch?: string;
      setUpstream?: boolean;
      dryRun?: boolean;
    } = {},
  ): Promise<string[]> {
    const cwd = options.cwd ?? this.cwd;
    const remote = options.remote ?? 'origin';
    const branch = options.branch ?? 'main';
    const args = options.setUpstream ? ['push', '-u', remote, branch] : ['push', remote, branch];
    const command = `git ${args.join(' ')}`;
    if (options.dryRun) {
      return [command];
    }
    await execa('git', args, { cwd, stdio: 'inherit' });
    return [command];
  }

  async generateIgnore(stacks: string[], cwd = this.cwd): Promise<void> {
    const fs = createFileSystem(cwd);
    const lines: string[] = ['# Generated by MyCLI', ''];
    lines.push(
      '# Node',
      'node_modules/',
      'dist/',
      'build/',
      'coverage/',
      '.env',
      '.env.*',
      '!.env.example',
      '.cache/',
      '*.log',
      '.DS_Store',
      '',
    );
    if (stacks.includes('next') || stacks.includes('react')) {
      lines.push('# Frontend', '.next/', 'out/', '.vite/', '');
    }
    if (stacks.includes('docker')) {
      lines.push('# Docker', 'docker-data/', '');
    }
    await fs.write('.gitignore', `${lines.join('\n')}\n`);
  }

  async generateAttributes(cwd = this.cwd): Promise<void> {
    const fs = createFileSystem(cwd);
    await fs.write(
      '.gitattributes',
      ['* text=auto eol=lf', '*.ts text eol=lf', '*.json text eol=lf', '*.md text eol=lf', ''].join(
        '\n',
      ),
    );
  }

  getBranchNames(strategy: BranchStrategy): string[] {
    switch (strategy) {
      case 'git-flow':
        return ['main', 'develop'];
      case 'github-flow':
        return ['main'];
      case 'trunk-based':
        return ['main'];
    }
  }

  async setupBranchStrategy(strategy: BranchStrategy, cwd = this.cwd): Promise<void> {
    if (strategy !== 'git-flow' || !(await this.isRepository(cwd))) {
      return;
    }
    if (!(await this.hasCommits(cwd))) {
      return;
    }
    const existing = await execa('git', ['branch', '--list', 'develop'], { cwd, reject: false });
    if (existing.stdout.trim()) {
      return;
    }
    await execa('git', ['branch', 'develop'], { cwd });
  }

  async generateCommunityFiles(options: GitCommunityOptions): Promise<string[]> {
    const cwd = options.cwd ?? this.cwd;
    const fs = createFileSystem(cwd);
    const templates = createTemplateEngine({
      filesystem: fs,
      templatesRoot: options.templatesRoot,
    });
    const data = {
      appName: options.appName,
      year: new Date().getFullYear(),
      defaultBranch: options.defaultBranch ?? 'main',
      commitConvention: options.commitConvention ?? 'conventional',
    };
    const written: string[] = [];

    for (const file of COMMUNITY_FILES) {
      const content = await templates.renderFile(file.template, { data });
      if (!options.dryRun) {
        await fs.write(file.out, content);
      }
      written.push(file.out);
    }

    if (options.includeSecurity !== false) {
      const security = await templates.renderFile('features/git/SECURITY.ejs', { data });
      if (!options.dryRun) {
        await fs.write('SECURITY.md', security);
      }
      written.push('SECURITY.md');
    }

    return written;
  }

  async setupHooks(options: GitHooksOptions): Promise<GitHooksResult> {
    const cwd = options.cwd ?? this.cwd;
    const fs = createFileSystem(cwd);
    const templates = createTemplateEngine({
      filesystem: fs,
      templatesRoot: options.templatesRoot,
    });
    const pm = options.packageManager ?? 'pnpm';
    const commands = hookCommands(pm);
    const data = {
      appName: options.appName,
      commitlintExtends: commitlintExtends(options.convention),
      commitConvention: options.convention,
      ...commands,
    };
    const written: string[] = [];

    for (const file of HOOK_FILES) {
      const content = await templates.renderFile(file.template, { data });
      if (!options.dryRun) {
        await fs.write(file.out, content);
      }
      written.push(file.out);
    }

    if (!options.dryRun) {
      await fs.writeJson(
        'lint-staged.config.json',
        {
          '*.{ts,tsx,js,jsx,json,md}': ['biome check --write --no-errors-on-unmatched'],
        },
        { overwrite: true },
      );
    }
    written.push('lint-staged.config.json');

    return {
      files: written,
      devDependencies: hooksDevDependencies(options.convention),
      scripts: { prepare: 'husky', commit: 'cz' },
    };
  }

  async isProviderCliAvailable(provider: GitProvider): Promise<boolean> {
    const adapter = getGitProviderAdapter(provider);
    if (!adapter) return false;
    return adapter.isAvailable();
  }

  async createRemoteRepo(options: CreateRemoteRepoOptions): Promise<CreateRemoteRepoResult> {
    if (options.provider === 'skip') {
      return { url: '', remoteName: 'origin', commands: [], executed: false };
    }

    const adapter = getGitProviderAdapter(options.provider);
    if (!adapter) {
      throw new MyCliError(`Unsupported git provider: ${options.provider}`, { code: 'GIT_ERROR' });
    }

    if (options.dryRun) {
      return adapter.planCreate(options);
    }

    return adapter.executeCreate(options);
  }

  async publishToRemote(options: PublishToRemoteOptions): Promise<PublishToRemoteResult> {
    const cwd = options.cwd ?? this.cwd;
    const branch = options.branch ?? 'main';
    const commands: string[] = [];
    let pushed = false;

    if (options.dryRun) {
      commands.push(
        `git init -b ${branch}`,
        'git add .',
        `git commit -m "${options.commitMessage ?? 'Initial commit'}"`,
      );
      const remote = await this.createRemoteRepo({ ...options, dryRun: true });
      commands.push(...remote.commands);
      if (options.push !== false && options.provider !== 'github') {
        commands.push(`git push -u origin ${branch}`);
      }
      return { ...remote, branch, pushed: false, commands };
    }

    if (!(await this.isRepository(cwd))) {
      await this.init({ cwd, defaultBranch: branch });
    }

    if (options.ensureCommit !== false && !(await this.hasCommits(cwd))) {
      await this.addAll(cwd);
      try {
        await this.commit(options.commitMessage ?? 'Initial commit', cwd);
      } catch {
        // nothing to commit
      }
    }

    const remote = await this.createRemoteRepo({ ...options, push: options.push });
    commands.push(...remote.commands);

    if (options.push !== false) {
      if (options.provider === 'github' && remote.executed) {
        pushed = true;
      } else if (remote.url && !remote.url.includes('<')) {
        if (options.provider !== 'gitlab') {
          await this.addRemote({ cwd, url: remote.url, name: remote.remoteName });
        }
        const pushCommands = await this.push({ cwd, branch, setUpstream: true });
        commands.push(...pushCommands);
        pushed = true;
      }
    }

    return { ...remote, branch, pushed, commands };
  }
}

export function createGitManager(options?: {
  cwd?: string;
  filesystem?: FileSystem;
}): GitManager {
  return new GitManager(options);
}
