import type { ConfigManager } from '@mycli-cli/config-manager';
import type { FileSystem } from '@mycli-cli/filesystem';
import type { MappedField, NameVariants } from '../types.js';
import {
  type DrizzleDialect,
  type MigrationPlan,
  type SqlDialect,
  buildCreateTableSql,
  buildDrizzleTableBlock,
  buildDrizzleTableSnippet,
  buildPrismaModelBlock,
  migrationTimestamp,
  toDrizzleDialect,
} from './sql.js';

export type OrmKind =
  | 'prisma'
  | 'drizzle'
  | 'typeorm'
  | 'sequelize'
  | 'mongoose'
  | 'mikroorm'
  | 'none';

export interface MigrationContext {
  config: ConfigManager;
  fs: FileSystem;
  dryRun: boolean;
}

export function resolveOrm(config: ConfigManager): OrmKind {
  const orm = config.get().orm ?? 'prisma';
  if (
    orm === 'prisma' ||
    orm === 'drizzle' ||
    orm === 'typeorm' ||
    orm === 'sequelize' ||
    orm === 'mongoose' ||
    orm === 'mikroorm'
  ) {
    return orm;
  }
  return 'prisma';
}

export function resolveSqlDialect(config: ConfigManager): SqlDialect {
  const database = config.get().database ?? 'postgresql';
  switch (database) {
    case 'mysql':
    case 'mariadb':
      return 'mysql';
    case 'sqlite':
      return 'sqlite';
    case 'sqlserver':
      return 'sqlserver';
    default:
      return 'postgresql';
  }
}

function resolveDrizzleDialect(config: ConfigManager): DrizzleDialect {
  return toDrizzleDialect(resolveSqlDialect(config));
}

export async function planMigration(
  ctx: MigrationContext,
  names: NameVariants,
  fields: MappedField[],
): Promise<MigrationPlan> {
  const orm = resolveOrm(ctx.config);
  const dialect = resolveSqlDialect(ctx.config);
  const drizzleDialect = resolveDrizzleDialect(ctx.config);
  const ts = migrationTimestamp();
  const migrationName = `create_${names.snakePlural}`;
  const sql = buildCreateTableSql(names, fields, dialect);

  switch (orm) {
    case 'drizzle':
      return {
        orm,
        files: [
          {
            path: `drizzle/${ts}_${migrationName}.sql`,
            content: `-- Generated by MyCLI\n${sql}`,
          },
        ],
        schemaUpdates: [
          {
            path: 'src/database/schema.ts',
            content: buildDrizzleTableBlock(names, fields, drizzleDialect),
            mergeContent: buildDrizzleTableSnippet(names, fields, drizzleDialect),
          },
        ],
      };
    case 'typeorm':
      return {
        orm,
        files: [
          {
            path: `src/database/migrations/${ts}-Create${names.pascalPlural}.ts`,
            content: buildTypeOrmMigration(names, fields, dialect),
          },
        ],
      };
    case 'sequelize':
      return {
        orm,
        files: [
          {
            path: `src/database/migrations/${ts}-create-${names.kebabPlural}.js`,
            content: buildSequelizeMigration(names, fields, dialect),
          },
        ],
      };
    case 'mongoose':
      return {
        orm,
        files: [
          {
            path: `src/database/migrations/${ts}-create-${names.kebabPlural}.ts`,
            content: buildMongooseMigration(names, fields),
          },
        ],
      };
    case 'mikroorm':
      return {
        orm,
        files: [
          {
            path: `src/database/migrations/Migration${ts}_Create${names.pascalPlural}.ts`,
            content: buildMikroOrmMigration(names, fields, dialect, ts),
          },
        ],
      };
  }

  return {
    orm: 'prisma',
    files: [
      {
        path: `prisma/migrations/${ts}_${migrationName}/migration.sql`,
        content: `-- Generated by MyCLI\n${sql}`,
      },
    ],
    schemaUpdates: [
      {
        path: 'prisma/schema.prisma',
        content: buildPrismaModelBlock(names, fields),
      },
    ],
  };
}

export async function applyMigrationPlan(
  ctx: MigrationContext,
  plan: MigrationPlan,
): Promise<Array<{ path: string; content: string; action: 'create' | 'update' }>> {
  const written: Array<{ path: string; content: string; action: 'create' | 'update' }> = [];

  for (const file of plan.files) {
    const exists = await ctx.fs.exists(file.path);
    if (exists) {
      continue;
    }
    if (!ctx.dryRun) {
      const dir = file.path.includes('/') ? file.path.slice(0, file.path.lastIndexOf('/')) : '.';
      await ctx.fs.ensureDir(dir);
      await ctx.fs.write(file.path, file.content);
    }
    written.push({ path: file.path, content: file.content, action: 'create' });
  }

  for (const update of plan.schemaUpdates ?? []) {
    const merged = await mergeSchemaSnippet(
      ctx,
      update.path,
      update.content,
      update.mergeContent,
      plan.orm,
    );
    if (!merged) {
      continue;
    }
    const exists = await ctx.fs.exists(update.path);
    if (!ctx.dryRun) {
      if (exists) {
        await ctx.fs.write(update.path, merged, { overwrite: true });
      } else {
        await ctx.fs.ensureDir(
          update.path.includes('/') ? update.path.slice(0, update.path.lastIndexOf('/')) : '.',
        );
        await ctx.fs.write(update.path, merged);
      }
    }
    written.push({
      path: update.path,
      content: merged,
      action: exists ? 'update' : 'create',
    });
  }

  return written;
}

async function mergeSchemaSnippet(
  ctx: MigrationContext,
  path: string,
  snippet: string,
  mergeContent: string | undefined,
  orm: string,
): Promise<string | null> {
  const append = mergeContent ?? snippet;

  if (!(await ctx.fs.exists(path))) {
    return snippet;
  }

  const existing = await ctx.fs.read(path);
  const marker =
    orm === 'prisma'
      ? snippet.match(/^model\s+(\w+)/m)?.[1]
      : append.match(/export const (\w+)/)?.[1];

  if (marker) {
    if (orm === 'prisma' && existing.includes(`model ${marker} `)) {
      return null;
    }
    if (orm !== 'prisma' && existing.includes(marker)) {
      return null;
    }
  }

  return `${existing.trimEnd()}\n\n${append}\n`;
}

function buildTypeOrmMigration(
  names: NameVariants,
  fields: MappedField[],
  dialect: SqlDialect,
): string {
  const table = names.snakePlural;
  const ts = migrationTimestamp();
  const columns = fields
    .map((field) => {
      const col = field.isRelation ? field.propertyName : field.name;
      const type =
        field.type === 'boolean'
          ? 'boolean'
          : field.type === 'int'
            ? 'int'
            : field.type === 'number' || field.type === 'float'
              ? 'double precision'
              : 'varchar';
      return `          { name: '${col}', type: '${type}', isNullable: ${field.optional ? 'true' : 'false'} }`;
    })
    .join(',\n');

  return `import { MigrationInterface, QueryRunner, Table } from 'typeorm';

export class Create${names.pascalPlural}${ts} implements MigrationInterface {
  name = 'Create${names.pascalPlural}${ts}';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: '${table}',
        columns: [
          { name: 'id', type: '${dialect === 'mysql' ? 'char' : 'uuid'}', isPrimary: true },
${columns},
          { name: 'created_at', type: 'timestamp', default: 'now()' },
          { name: 'updated_at', type: 'timestamp', default: 'now()' },
        ],
      }),
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropTable('${table}');
  }
}
`;
}

function buildSequelizeMigration(
  names: NameVariants,
  fields: MappedField[],
  _dialect: SqlDialect,
): string {
  const attrs = fields
    .map((field) => {
      const key = field.isRelation ? field.propertyName : field.name;
      const type =
        field.type === 'boolean'
          ? 'Sequelize.BOOLEAN'
          : field.type === 'int' || field.type === 'number'
            ? 'Sequelize.INTEGER'
            : field.type === 'float'
              ? 'Sequelize.DOUBLE'
              : 'Sequelize.STRING';
      return `      ${key}: { type: ${type}, allowNull: ${field.optional ? 'true' : 'false'} }`;
    })
    .join(',\n');

  return `/** @type {import('sequelize-cli').Migration} */
export default {
  async up(queryInterface, Sequelize) {
    await queryInterface.createTable('${names.snakePlural}', {
      id: {
        type: Sequelize.UUID,
        defaultValue: Sequelize.UUIDV4,
        primaryKey: true,
      },
${attrs},
      created_at: { type: Sequelize.DATE, allowNull: false },
      updated_at: { type: Sequelize.DATE, allowNull: false },
    });
  },

  async down(queryInterface) {
    await queryInterface.dropTable('${names.snakePlural}');
  },
};
`;
}

function buildMongooseMigration(names: NameVariants, fields: MappedField[]): string {
  const schemaFields = fields
    .map((field) => {
      const key = field.isRelation ? field.propertyName : field.name;
      const type =
        field.type === 'boolean'
          ? 'Boolean'
          : field.type === 'int' || field.type === 'number' || field.type === 'float'
            ? 'Number'
            : 'String';
      return `    ${key}: { type: ${type}, required: ${field.optional ? 'false' : 'true'} }`;
    })
    .join(',\n');

  return `/**
 * MongoDB collection bootstrap for ${names.pascalPlural}
 * Generated by MyCLI
 */
import mongoose from 'mongoose';

const ${names.pascal}Schema = new mongoose.Schema(
  {
${schemaFields},
  },
  { timestamps: true, collection: '${names.snakePlural}' },
);

export async function up(): Promise<void> {
  await mongoose.model('${names.pascal}', ${names.pascal}Schema).createCollection();
}

export async function down(): Promise<void> {
  await mongoose.connection.dropCollection('${names.snakePlural}');
}
`;
}

function buildMikroOrmMigration(
  names: NameVariants,
  fields: MappedField[],
  dialect: SqlDialect,
  ts: string,
): string {
  const sql = buildCreateTableSql(names, fields, dialect)
    .replace(/IF NOT EXISTS /g, '')
    .trim()
    .replace(/;$/, '');

  return `import { Migration } from '@mikro-orm/migrations';

export class Migration${ts}_Create${names.pascalPlural} extends Migration {
  async up(): Promise<void> {
    this.addSql(\`${sql.replace(/`/g, '\\`')}\`);
  }

  async down(): Promise<void> {
    this.addSql('DROP TABLE IF EXISTS "${names.snakePlural}";');
  }
}
`;
}
