import type { ArchitectureDependencyRulesFile, DependencyRule } from '@mycli/enterprise-core';

export interface EslintArchitectureConfig {
  filename: string;
  content: string;
}

/**
 * Build ESLint flat config that enforces architecture import boundaries via no-restricted-imports.
 */
export function buildEslintArchitectureConfig(
  rulesFile: ArchitectureDependencyRulesFile,
): EslintArchitectureConfig {
  const zones = rulesFile.rules.flatMap((rule) => buildZonesForRule(rule));

  const content = `/**
 * Architecture boundary rules for ${rulesFile.appName} (${rulesFile.style})
 * Generated by MyCLI — merge into eslint.config.js:
 *
 *   import architectureConfig from './eslint.architecture.config.js';
 *   export default [...architectureConfig, ...yourConfig];
 */
export default [
  {
    files: ['src/**/*.{ts,tsx,js,jsx}', 'services/**/*.{ts,tsx,js,jsx}', 'shared/**/*.{ts,tsx,js,jsx}'],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          patterns: ${JSON.stringify(zones, null, 2)},
        },
      ],
    },
  },
];
`;

  return { filename: 'eslint.architecture.config.js', content };
}

function buildZonesForRule(rule: DependencyRule): Array<{ group: string[]; message: string }> {
  const patterns: Array<{ group: string[]; message: string }> = [];
  const targetGlob = rule.path.endsWith('/*') ? `${rule.path}/**` : `${rule.path}/**`;

  for (const forbidden of rule.mustNotImport) {
    const pattern =
      forbidden.startsWith('src/') || forbidden.startsWith('services/')
        ? `${forbidden}/**`
        : forbidden;
    patterns.push({
      group: [pattern],
      message: `[${rule.layer}] ${rule.description}`,
    });
  }

  if (patterns.length === 0) return [];

  return patterns.map((p) => ({
    group: p.group,
    message: `${p.message} (applies under ${targetGlob})`,
  }));
}
